# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QSMGi8pI0mdomzNZSGxXSYk0c6E2ShGM
"""

key = "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"

import os
os.environ["GOOGLE_API_KEY"] = key

from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage
import os

# Set your Groq API key
os.environ["GROQ_API_KEY"] = key

# Initialize Groq LLM
llm = ChatOpenAI(
    model="llama-3.3-70b-versatile",
    base_url="https://api.groq.com/openai/v1",
    api_key=os.environ["GROQ_API_KEY"],
    temperature=0.3
)

# Send prompt
response = llm.invoke([
    HumanMessage(content="Explain feature selection in machine learning briefly")
])

print(response.content)

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

!pip3 install langchain-openai

